name: Build & Publish Docker Hub/Github
on:
  release:
    types: [published]
jobs:
  push_to_registries_hub:
    name: Build & Publish Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set ENVs
        run: echo "Tags are > ${DOCKERFILE}"
        env:
          DOCKERFILE: "./Dockerfile"
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}     
        
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        id: dockerhub_build
        uses: docker/build-push-action@v2 
        with:
          file: ${{ env.DOCKERFILES }}
          push: true
          tags: ${{ github.repository }}:${{ steps.get_tag_name.outputs.VERSION }}
  push_to_registries_github:
    name: Build & Publish Docker Github
    runs-on: ubuntu-latest
    steps:
      - name: Set ENVs
        run: echo "Tags are > ${DOCKERFILE}"
        env:
          DOCKERFILE: "./Dockerfile"
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}     
        
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}          
      -
        name: Login to GitHub Packages Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUBR_USERNAME }}
          password: ${{ secrets.GITHUBR_TOKEN }}  
            
      - name: Build and Push to Github Container Registry
        id: dockergithub_build
        uses: docker/build-push-action@v2 
        with:
          file: ${{ env.DOCKERFILES }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.get_tag_name.outputs.VERSION }}
