name: Build & Publish Docker
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Build & Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Set ENVs
        if: ! ${{ env.DOCKERFILE }}
        env:
          DOCKERFILE: "./Dockerfile"
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2 
        with:
          Dockerfile: ${{ env.DOCKERFILES }}
          push: true
          tags: hub.docker.com/${{ github.repsotory }}:${{ github.ref }}
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repsotory }}:${{ github.ref }} 
          tag_with_ref: true
