name: Docker Checks
on: pull_request
jobs:
  check_docker:
    name: Check Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Set ENVs
        run: echo "Tags are > ${DOCKERFILE}"
        env:
          DOCKERFILE: "./Dockerfile"
      - name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to Docker Hub
        id: dockerhub_build
        uses: docker/build-push-action@v2
        with:
          file: ${{ env.DOCKERFILES }}
          tags: audit

      - name: Install Dockle
        run: |
          DOCKLE_VERSION=$(
            curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/' \
          );
          curl -L -s -o "dockle_${DOCKLE_VERSION}_Linux-64bit.tar.gz" https://github.com/goodwithtech/dockle/releases/download/v${DOCKLE_VERSION}/dockle_${DOCKLE_VERSION}_Linux-64bit.tar.gz
          tar -xzvf dockle_${DOCKLE_VERSION}_Linux-64bit.tar.gz > /dev/null && mv dockle /usr/local/bin/ && chmod +x /usr/local/bin/dockle

      - name: Audit image
        run: |
         dockle --exit-code 1 --exit-level FATAL audit
